# KingdomWars by Elian & Silverwolfg11 #
########################################

# How much money it costs to start a war
start-amount: 25000

# How much money does the winning nation recieve?
win-amount: 100000

# How much money is lost when a nation loses?
lose-amount: 10000

# Should the declaring nation receive the starting amount back if they win?
receive-start-amount-back: true

# How much money is awarded/taken away when war ends by truce
truce-amount: 50000

# How many kills a nation must receive to win the war
winning-kills: 25

# Time between declaring a war and the war starting (in mins)
preparation-time: 5

# When a nation calls allies, the time between the call and when the war starts (in mins)
ally-prep-time: 10

# Grace Period. How much time does a new nation have before they can get warred? (in mins)
grace-period: 10

# Hours between two nations can war again
hours-between: 168

# Hours between a nation can enact revenge on one it just warred (like starting another war but quicker)
hours-between-revenge: 72

# Hours before a war must end
hours-end: 168

#The amount of more kills needed for every ally that joins a war
ally-bonus-kills: 5

# Town block bonus for winning
town-block-bonus: 10

# How many town blocks should the losing nation lose?
town-block-loss: 10

# What's the minimum number of town blocks a nation can lose?
town-block-min: 40

# What's the maximum number of town blocks a nation can win?
town-block-max: 90