main: net.urbanmc.kingdomwars.KingdomWars
name: KingdomWars
version: 1.1
authors: [Elian, Silverwolfg11]
api-version: 1.14
description: Allows for individual wars between nations
softdepend: [Essentials, Towny, Vault]

permissions:
  kingdomwars.*:
    default: op
    children:
      kingdomwars.nationstaff: true
      kingdomwars.forceend: true
      kingdomwars.forcestart: true
      kingdomwars.last: true
      kingdomwars.reload: true
      kingdomwars.warblocks: true
      kingdomwars.archive.refresh: true
      kingdomwars.archive.remove: true
      kingdomwars.war: true
      kingdomwars.ally: true

  kingdomwars.nationstaff:
    default: false
    children:
      kingdomwars.nationres: true
      kingdomwars.start: true
      kingdomwars.end: true
      kingdomwars.truce: true
      kingdomwars.joinwar: true
      kingdomwars.callallies: true

  kingdomwars.nationres:
    default: false
    children:
      kingdomwars.status: true
      kingdomwars.wars: true
      kingdomwars.leaderboard: true
      kingdomwars.archive: true
      kingdomwars.archive.id: true
      kingdomwars.archive.nation: true

  kingdomwars.start:
    default: false
  kingdomwars.end:
    default: false
  kingdomwars.truce:
    default: false
  kingdomwars.status:
    default: false
  kingdomwars.forceend:
    default: false
  kingdomwars.wars:
    default: false
  kingdomwars.leaderboard:
    default: false
  kingdomwars.joinwar:
    default: false
  kingdomwars.callallies:
    default: false
  kingdomwars.reload:
    default: false
  kingdomwars.warblocks:
    default: false
  kingdomwars.archive:
    default: false
  kingdomwars.archive.nation:
    default: false
  kingdomwars.archive.id:
    default: false
  kingdomwars.archive.refresh:
    default: false
  kingdomwars.archive.remove:
    default: false
  kingdomwars.ally:
    default: false
  kingdomwars.war:
    default: false