main: net.urbanmc.kindomwars.KingdomWars
name: TownWars
version: 1.0
authors: [Elian, Silverwolfg11]
description: Allows for individual wars between nations
softdepend: [Towny]

commands:
  townywar:
    description: Manage your nation's wars
    aliases: [twar, twars]